### PR TITLE
Added various mods and tweaked little parameters

### PR DESCRIPTION
**Pull request by Lymkwi**
- Gravity override is now 0.1 to allow players jumping and skeaking
- A calandria:light node is placed when generating at (0,0,0)
- Added creative mod from minetest_game
- Created a little mod containing items used so that players can change their gravity override
- Added worldedit
- Tweaked worldedit to add //cone

### CODE REVIEW

**Comment by technomancy** [comment]
Looks great; thanks! Feel free to open issues discussing further ideas for development.

**Comment by technomancy** [comment]
I'm trying to use the gravity items, but I don't seem to be able to place them with right-clicking. Is there a trick to this; maybe some limitations on where they can be placed?

**Comment by Lymkwi** [comment]
You must left-click while holding them to get the gravity override applied. These are craft_items, they can't be placed. Also, items overriding players around them would be nice, but maybe a bit heavy on the memory side.

**Comment by technomancy** [comment]
I see; thanks for the clarification.

**Pull request merged**
